---
env:
  browser: true
  es6: true
  jest: true

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

extends:
  - plugin:react/recommended
  - ../.eslintrc.yaml

plugins:
  - react

rules:
  react/display-name: 0
  react/jsx-filename-extension:
    - error
  react/jsx-pascal-case:
    - error
  react/jsx-boolean-value: error
  react/jsx-one-expression-per-line:
    - off
  react/jsx-closing-bracket-location:
    - error
    - line-aligned
  react/jsx-max-props-per-line:
    - error
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-wrap-multilines:
    - error
    - declaration: parens-new-line
      assignment: parens-new-line
      return: parens-new-line
      arrow: parens-new-line
      condition: parens-new-line
      logical: parens-new-line
      prop: parens-new-line
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-tag-spacing:
  - error
  react/jsx-curly-spacing:
    - error
    - when: always
      children: true
      spacing:
        objectLiterals: always
  react/prop-types: off
  no-console:
    - error
  no-extra-parens:
    - error
    - all
    - enforceForArrowConditionals: false
      ignoreJSX: all
overrides:
  - files:
    - src/**/*.spec{.jsx,.js}
    rules:
      max-nested-callbacks: 'off'

  - files:
    - config/*.js
    - webpack.config.js

    rules:
      no-console: 'off'
      camelcase: 'off'
