---
root: true

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

env:
  node: true
  es6: true

extends:
- eslint:recommended

rules:
  no-extra-parens:
    - error
    - all
    - enforceForArrowConditionals: false
  dot-notation: error
  dot-location:
    - error
    - property
  eqeqeq: error
  curly: error
  consistent-return: error
  complexity:
    - error
    - max: 5
  no-multi-spaces: error
  no-extra-bind: error
  no-undefined: error
  camelcase: error
  func-names:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  func-style: error
  key-spacing: error
  keyword-spacing: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  max-depth:
    - error
    - 2
  max-len:
    - error
    - 150
  max-lines:
    - warn
    - 300
  max-nested-callbacks:
    - error
    - 3
  max-params:
    - error
    - 3
  max-statements:
    - error
    - 15
  max-statements-per-line:
    - error
    - max: 1
  multiline-ternary:
    - error
    - always-multiline
  new-parens: error
  no-multi-assign: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
  no-negated-condition: error
  no-nested-ternary: error
  no-tabs: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  operator-linebreak:
   - error
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi: error
  semi-spacing: error
  semi-style: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  no-confusing-arrow:
    - error
    - allowParens: true
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: warn
  prefer-const: error
  prefer-template: error
  rest-spread-spacing: error
  template-curly-spacing:
    - error
    - always
  no-console:
    - off

overrides:
- files:
  - client/**/*.spec{.jsx,.js}
  - server/**/*.spec{.jsx,.js}
  rules:
    max-nested-callbacks: 'off'
  env:
    jest: true
